import Std.Tactic.BVDecide

namespace CL8E8TQC.BellSAT.CortezKS

open BitVec

/-!
# Cortez-Morales-Reyes Kochen-Specker Uncolorability Theorem

## Abstract

The Kochen-Specker (KS) theorem is a fundamental result in quantum mechanics asserting the contextuality of measurement. It proves that non-contextual hidden variable theories — those positing that all observables possess definite pre-measurement values — are incompatible with quantum mechanics. This file adopts the Cortez-Morales-Reyes construction (arXiv:2211.13216, Theorem 5(2)) over $\mathbb{Z}^6$ with integer vectors (86 variables and 121 orthogonality contexts) and mechanically proves KS uncolorability via Lean 4's `bv_decide` tactic. The search space $2^{86} \approx 7.7 \times 10^{25}$ is exhaustively covered by CaDiCaL SAT solver with LRAT proof certificate verification, and the non-existence of any non-contextual coloring (UNSAT) is guaranteed purely functionally by Lean's kernel type checker.

## 1. Introduction

Constraints on hidden variable theories in quantum mechanics have developed along two lineages: Bell inequalities (1964) and the Kochen-Specker theorem (1967). Whereas Bell inequalities impose statistical constraints on correlations between spatially separated systems, the KS theorem provides a combinatorial constraint on the context-dependence of measurements within a single system. Specifically, the KS theorem asserts that it is impossible to assign definite values to observables independently of the measurement context, and this is formalized as logical unsatisfiability (UNSAT) over a search space.

The Cortez-Morales-Reyes (2025) construction adopted by this module is computationally superior to prior KS constructions (Kochen-Specker's 117 vectors, Conway-Kochen's 31 vectors, etc.) in that it uses only integer arithmetic over $\mathbb{Z}^6$. Orthogonality of integer vectors is defined by the exact vanishing of the inner product, so no floating-point error can intervene. This aligns perfectly with mechanical proofs at the bit-operation level via Lean 4's `bv_decide` tactic, and it is deeply consonant with the Forbidden Float principle of the CL8E8TQC theory as a whole.

Within the context of the CL8E8TQC theory, the KS proof in this module is not merely an isolated formal verification; it provides the algebraic grounds showing that the Cl(8) geometric product structure inherently transcends any non-contextual description. Together with the CHSH violation proof ($S^2 = 65536 > 4K^2 = 32768$) established by `native_decide` in `_01_QuantumCHSH.lean` within the same `_02_BellSAT` module, this module group constitutes the formal foundation for quantum nonlocality in CL8E8TQC.

## 2. Relation to Prior Work

| KS Construction | Vectors | Contexts | Dimension | Integer Arithmetic | Machine Proof |
|:---|:---|:---|:---|:---|:---|
| Kochen-Specker (1967) | 117 | — | $\mathbb{R}^3$ | No (reals) | None |
| Conway-Kochen | 31 | — | $\mathbb{R}^3$ | No (reals) | None |
| Peres (1991) | 33 | — | $\mathbb{R}^3$ | No (reals) | None |
| Cabello et al. (1996) | 18 | 9 | $\mathbb{R}^4$ | No (reals) | None |
| **Cortez-Morales-Reyes (2025)** | **86** | **121** | **$\mathbb{Z}^6$** | **Yes (integers only)** | **`bv_decide` (this file)** |

- This implementation uses Lean 4's `bv_decide` tactic (CaDiCaL + LRAT verification), making it one of the first formal KS proofs whose entire mathematical argument is re-verifiable by the Lean kernel.
- The `maxHeartbeats 100000000` setting (500× the default) accommodates the kernel computation required for the scale of 86 variables × 121 contexts, without compromising the trustworthiness of the proof.
- The H(8,4) algebraic structure established in `_01_TQC/_01_Cl8E8H84.lean`, combined with the quantum contextuality proof in this module and the CHSH formal proof in `_01_QuantumCHSH.lean`, demonstrates that Cl(8) intrinsically realizes quantum correlations.

## 3. Contributions of This Chapter

- **Machine proof of the KS uncolorability theorem**: Formally proves via `bv_decide` that the SAT encoding of 86 variables and 121 orthogonality contexts is UNSAT.
- **Exhaustive search-space coverage**: Guarantees that all $2^{86} \approx 7.7 \times 10^{25}$ colorings violate the KS conditions.
- **Exactness via integer arithmetic**: Reduces $\mathbb{Z}^6$ inner-product zero-testing to bit operations, upholding the Forbidden Float principle throughout.
- **Independent verification by the Lean kernel**: The LRAT proof certificate output by the CaDiCaL SAT solver is re-verified purely functionally by the Lean type checker.
- **Connection to CL8E8TQC**: Shows that the formal proof of quantum contextuality constitutes the algebraic grounds for the impossibility of non-contextual descriptions of Cl(8).
- **Proof scale**: The theorem `cortez_121_unsat` handles all 121 context constraints simultaneously in a single `bv_decide` invocation.

## 4. Chapter Structure

| Section | Content |
|:---|:---|
| §1. Large-scale SAT theorem | `cortez_121_unsat`: Machine proof body for KS uncolorability with 86 variables and 121 contexts |
| §Appendix (reference section) | References and inter-module connections |

## How `bv_decide` Works and Build Cost

**Important**: The first build of this file takes **several minutes to tens of minutes**. This is due to the proof mechanism of `bv_decide`:

## Three-Stage Proof Process

1. **CNF conversion**: The theorem statement (a logical formula over `BitVec 86`) is converted to conjunctive normal form (CNF). This step is fast.

2. **SAT solver invocation**: The external SAT solver (CaDiCaL) is launched and uses the CDCL (Conflict-Driven Clause Learning) algorithm to determine UNSAT (unsatisfiability). This completes in seconds.

3. **LRAT proof certificate verification**: The LRAT (Lean RAT) proof certificate output by the SAT solver is **re-verified purely functionally** by Lean's kernel (type checker). This stage is the bottleneck and takes several minutes to tens of minutes.

### Why Is It Slow?

The SAT solver itself is an efficient C implementation and runs fast, but the LRAT certificate — its "evidence of correctness" — can be enormous (on the order of hundreds of megabytes). Lean's type checker must verify this certificate line by line, which is what takes time.

## Subsequent Builds

Since an `.olean` file is generated during the first build, **subsequent builds complete instantaneously**.

### `maxHeartbeats` Setting

`set_option maxHeartbeats 100000000` permits **500× the default** computation budget. This is necessary for the scale of the KS-SAT proof (86 variables × 121 contexts).

## Tags

kochen-specker, contextuality, bv-decide, sat-proof, uncolorability

---

# §1. Large-Scale SAT Theorem

The code below is auto-generated. It proves that no coloring of the 86 vectors can simultaneously satisfy the "exactly one true" constraint across all 121 orthogonality contexts — i.e., the problem is **unsatisfiable** (UNSAT).
-/

-- bv_decide computation budget: 500× the default
set_option maxHeartbeats 100000000
set_option maxRecDepth 10000

-- GENERATED: This theorem statement is auto-generated; do not edit manually

theorem cortez_121_unsat : ∀ (c : BitVec 86),
  (((c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 5) || (!c.getLsbD 0 && c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 5) || (!c.getLsbD 0 && !c.getLsbD 1 && c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 5) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 2 && c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 5) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 3 && c.getLsbD 4 && !c.getLsbD 5) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 4 && c.getLsbD 5)) &&
   ((c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 70 && !c.getLsbD 76 && !c.getLsbD 81 && !c.getLsbD 83) || (!c.getLsbD 0 && c.getLsbD 1 && !c.getLsbD 70 && !c.getLsbD 76 && !c.getLsbD 81 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 1 && c.getLsbD 70 && !c.getLsbD 76 && !c.getLsbD 81 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 70 && c.getLsbD 76 && !c.getLsbD 81 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 70 && !c.getLsbD 76 && c.getLsbD 81 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 70 && !c.getLsbD 76 && !c.getLsbD 81 && c.getLsbD 83)) &&
   ((c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 70 && !c.getLsbD 77 && !c.getLsbD 80 && !c.getLsbD 82) || (!c.getLsbD 0 && c.getLsbD 1 && !c.getLsbD 70 && !c.getLsbD 77 && !c.getLsbD 80 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 1 && c.getLsbD 70 && !c.getLsbD 77 && !c.getLsbD 80 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 70 && c.getLsbD 77 && !c.getLsbD 80 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 70 && !c.getLsbD 77 && c.getLsbD 80 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 70 && !c.getLsbD 77 && !c.getLsbD 80 && c.getLsbD 82)) &&
   ((c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 71 && !c.getLsbD 76 && !c.getLsbD 79 && !c.getLsbD 85) || (!c.getLsbD 0 && c.getLsbD 1 && !c.getLsbD 71 && !c.getLsbD 76 && !c.getLsbD 79 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 1 && c.getLsbD 71 && !c.getLsbD 76 && !c.getLsbD 79 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 71 && c.getLsbD 76 && !c.getLsbD 79 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 71 && !c.getLsbD 76 && c.getLsbD 79 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 71 && !c.getLsbD 76 && !c.getLsbD 79 && c.getLsbD 85)) &&
   ((c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 71 && !c.getLsbD 77 && !c.getLsbD 78 && !c.getLsbD 84) || (!c.getLsbD 0 && c.getLsbD 1 && !c.getLsbD 71 && !c.getLsbD 77 && !c.getLsbD 78 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 1 && c.getLsbD 71 && !c.getLsbD 77 && !c.getLsbD 78 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 71 && c.getLsbD 77 && !c.getLsbD 78 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 71 && !c.getLsbD 77 && c.getLsbD 78 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 71 && !c.getLsbD 77 && !c.getLsbD 78 && c.getLsbD 84)) &&
   ((c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 72 && !c.getLsbD 74 && !c.getLsbD 81 && !c.getLsbD 84) || (!c.getLsbD 0 && c.getLsbD 1 && !c.getLsbD 72 && !c.getLsbD 74 && !c.getLsbD 81 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 1 && c.getLsbD 72 && !c.getLsbD 74 && !c.getLsbD 81 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 72 && c.getLsbD 74 && !c.getLsbD 81 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 72 && !c.getLsbD 74 && c.getLsbD 81 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 72 && !c.getLsbD 74 && !c.getLsbD 81 && c.getLsbD 84)) &&
   ((c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 72 && !c.getLsbD 75 && !c.getLsbD 80 && !c.getLsbD 85) || (!c.getLsbD 0 && c.getLsbD 1 && !c.getLsbD 72 && !c.getLsbD 75 && !c.getLsbD 80 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 1 && c.getLsbD 72 && !c.getLsbD 75 && !c.getLsbD 80 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 72 && c.getLsbD 75 && !c.getLsbD 80 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 72 && !c.getLsbD 75 && c.getLsbD 80 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 72 && !c.getLsbD 75 && !c.getLsbD 80 && c.getLsbD 85)) &&
   ((c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 73 && !c.getLsbD 74 && !c.getLsbD 79 && !c.getLsbD 82) || (!c.getLsbD 0 && c.getLsbD 1 && !c.getLsbD 73 && !c.getLsbD 74 && !c.getLsbD 79 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 1 && c.getLsbD 73 && !c.getLsbD 74 && !c.getLsbD 79 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 73 && c.getLsbD 74 && !c.getLsbD 79 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 73 && !c.getLsbD 74 && c.getLsbD 79 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 73 && !c.getLsbD 74 && !c.getLsbD 79 && c.getLsbD 82)) &&
   ((c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 73 && !c.getLsbD 75 && !c.getLsbD 78 && !c.getLsbD 83) || (!c.getLsbD 0 && c.getLsbD 1 && !c.getLsbD 73 && !c.getLsbD 75 && !c.getLsbD 78 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 1 && c.getLsbD 73 && !c.getLsbD 75 && !c.getLsbD 78 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 73 && c.getLsbD 75 && !c.getLsbD 78 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 73 && !c.getLsbD 75 && c.getLsbD 78 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 1 && !c.getLsbD 73 && !c.getLsbD 75 && !c.getLsbD 78 && c.getLsbD 83)) &&
   ((c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 58 && !c.getLsbD 64 && !c.getLsbD 69 && !c.getLsbD 83) || (!c.getLsbD 0 && c.getLsbD 2 && !c.getLsbD 58 && !c.getLsbD 64 && !c.getLsbD 69 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 2 && c.getLsbD 58 && !c.getLsbD 64 && !c.getLsbD 69 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 58 && c.getLsbD 64 && !c.getLsbD 69 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 58 && !c.getLsbD 64 && c.getLsbD 69 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 58 && !c.getLsbD 64 && !c.getLsbD 69 && c.getLsbD 83)) &&
   ((c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 58 && !c.getLsbD 65 && !c.getLsbD 68 && !c.getLsbD 82) || (!c.getLsbD 0 && c.getLsbD 2 && !c.getLsbD 58 && !c.getLsbD 65 && !c.getLsbD 68 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 2 && c.getLsbD 58 && !c.getLsbD 65 && !c.getLsbD 68 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 58 && c.getLsbD 65 && !c.getLsbD 68 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 58 && !c.getLsbD 65 && c.getLsbD 68 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 58 && !c.getLsbD 65 && !c.getLsbD 68 && c.getLsbD 82)) &&
   ((c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 59 && !c.getLsbD 64 && !c.getLsbD 67 && !c.getLsbD 85) || (!c.getLsbD 0 && c.getLsbD 2 && !c.getLsbD 59 && !c.getLsbD 64 && !c.getLsbD 67 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 2 && c.getLsbD 59 && !c.getLsbD 64 && !c.getLsbD 67 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 59 && c.getLsbD 64 && !c.getLsbD 67 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 59 && !c.getLsbD 64 && c.getLsbD 67 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 59 && !c.getLsbD 64 && !c.getLsbD 67 && c.getLsbD 85)) &&
   ((c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 59 && !c.getLsbD 65 && !c.getLsbD 66 && !c.getLsbD 84) || (!c.getLsbD 0 && c.getLsbD 2 && !c.getLsbD 59 && !c.getLsbD 65 && !c.getLsbD 66 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 2 && c.getLsbD 59 && !c.getLsbD 65 && !c.getLsbD 66 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 59 && c.getLsbD 65 && !c.getLsbD 66 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 59 && !c.getLsbD 65 && c.getLsbD 66 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 59 && !c.getLsbD 65 && !c.getLsbD 66 && c.getLsbD 84)) &&
   ((c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 60 && !c.getLsbD 62 && !c.getLsbD 69 && !c.getLsbD 84) || (!c.getLsbD 0 && c.getLsbD 2 && !c.getLsbD 60 && !c.getLsbD 62 && !c.getLsbD 69 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 2 && c.getLsbD 60 && !c.getLsbD 62 && !c.getLsbD 69 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 60 && c.getLsbD 62 && !c.getLsbD 69 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 60 && !c.getLsbD 62 && c.getLsbD 69 && !c.getLsbD 84) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 60 && !c.getLsbD 62 && !c.getLsbD 69 && c.getLsbD 84)) &&
   ((c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 60 && !c.getLsbD 63 && !c.getLsbD 68 && !c.getLsbD 85) || (!c.getLsbD 0 && c.getLsbD 2 && !c.getLsbD 60 && !c.getLsbD 63 && !c.getLsbD 68 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 2 && c.getLsbD 60 && !c.getLsbD 63 && !c.getLsbD 68 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 60 && c.getLsbD 63 && !c.getLsbD 68 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 60 && !c.getLsbD 63 && c.getLsbD 68 && !c.getLsbD 85) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 60 && !c.getLsbD 63 && !c.getLsbD 68 && c.getLsbD 85)) &&
   ((c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 61 && !c.getLsbD 62 && !c.getLsbD 67 && !c.getLsbD 82) || (!c.getLsbD 0 && c.getLsbD 2 && !c.getLsbD 61 && !c.getLsbD 62 && !c.getLsbD 67 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 2 && c.getLsbD 61 && !c.getLsbD 62 && !c.getLsbD 67 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 61 && c.getLsbD 62 && !c.getLsbD 67 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 61 && !c.getLsbD 62 && c.getLsbD 67 && !c.getLsbD 82) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 61 && !c.getLsbD 62 && !c.getLsbD 67 && c.getLsbD 82)) &&
   ((c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 61 && !c.getLsbD 63 && !c.getLsbD 66 && !c.getLsbD 83) || (!c.getLsbD 0 && c.getLsbD 2 && !c.getLsbD 61 && !c.getLsbD 63 && !c.getLsbD 66 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 2 && c.getLsbD 61 && !c.getLsbD 63 && !c.getLsbD 66 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 61 && c.getLsbD 63 && !c.getLsbD 66 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 61 && !c.getLsbD 63 && c.getLsbD 66 && !c.getLsbD 83) || (!c.getLsbD 0 && !c.getLsbD 2 && !c.getLsbD 61 && !c.getLsbD 63 && !c.getLsbD 66 && c.getLsbD 83)) &&
   ((c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 50 && !c.getLsbD 56 && !c.getLsbD 69 && !c.getLsbD 79) || (!c.getLsbD 0 && c.getLsbD 3 && !c.getLsbD 50 && !c.getLsbD 56 && !c.getLsbD 69 && !c.getLsbD 79) || (!c.getLsbD 0 && !c.getLsbD 3 && c.getLsbD 50 && !c.getLsbD 56 && !c.getLsbD 69 && !c.getLsbD 79) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 50 && c.getLsbD 56 && !c.getLsbD 69 && !c.getLsbD 79) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 50 && !c.getLsbD 56 && c.getLsbD 69 && !c.getLsbD 79) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 50 && !c.getLsbD 56 && !c.getLsbD 69 && c.getLsbD 79)) &&
   ((c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 50 && !c.getLsbD 57 && !c.getLsbD 68 && !c.getLsbD 78) || (!c.getLsbD 0 && c.getLsbD 3 && !c.getLsbD 50 && !c.getLsbD 57 && !c.getLsbD 68 && !c.getLsbD 78) || (!c.getLsbD 0 && !c.getLsbD 3 && c.getLsbD 50 && !c.getLsbD 57 && !c.getLsbD 68 && !c.getLsbD 78) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 50 && c.getLsbD 57 && !c.getLsbD 68 && !c.getLsbD 78) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 50 && !c.getLsbD 57 && c.getLsbD 68 && !c.getLsbD 78) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 50 && !c.getLsbD 57 && !c.getLsbD 68 && c.getLsbD 78)) &&
   ((c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 51 && !c.getLsbD 56 && !c.getLsbD 67 && !c.getLsbD 81) || (!c.getLsbD 0 && c.getLsbD 3 && !c.getLsbD 51 && !c.getLsbD 56 && !c.getLsbD 67 && !c.getLsbD 81) || (!c.getLsbD 0 && !c.getLsbD 3 && c.getLsbD 51 && !c.getLsbD 56 && !c.getLsbD 67 && !c.getLsbD 81) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 51 && c.getLsbD 56 && !c.getLsbD 67 && !c.getLsbD 81) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 51 && !c.getLsbD 56 && c.getLsbD 67 && !c.getLsbD 81) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 51 && !c.getLsbD 56 && !c.getLsbD 67 && c.getLsbD 81)) &&
   ((c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 51 && !c.getLsbD 57 && !c.getLsbD 66 && !c.getLsbD 80) || (!c.getLsbD 0 && c.getLsbD 3 && !c.getLsbD 51 && !c.getLsbD 57 && !c.getLsbD 66 && !c.getLsbD 80) || (!c.getLsbD 0 && !c.getLsbD 3 && c.getLsbD 51 && !c.getLsbD 57 && !c.getLsbD 66 && !c.getLsbD 80) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 51 && c.getLsbD 57 && !c.getLsbD 66 && !c.getLsbD 80) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 51 && !c.getLsbD 57 && c.getLsbD 66 && !c.getLsbD 80) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 51 && !c.getLsbD 57 && !c.getLsbD 66 && c.getLsbD 80)) &&
   ((c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 52 && !c.getLsbD 54 && !c.getLsbD 69 && !c.getLsbD 80) || (!c.getLsbD 0 && c.getLsbD 3 && !c.getLsbD 52 && !c.getLsbD 54 && !c.getLsbD 69 && !c.getLsbD 80) || (!c.getLsbD 0 && !c.getLsbD 3 && c.getLsbD 52 && !c.getLsbD 54 && !c.getLsbD 69 && !c.getLsbD 80) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 52 && c.getLsbD 54 && !c.getLsbD 69 && !c.getLsbD 80) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 52 && !c.getLsbD 54 && c.getLsbD 69 && !c.getLsbD 80) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 52 && !c.getLsbD 54 && !c.getLsbD 69 && c.getLsbD 80)) &&
   ((c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 52 && !c.getLsbD 55 && !c.getLsbD 68 && !c.getLsbD 81) || (!c.getLsbD 0 && c.getLsbD 3 && !c.getLsbD 52 && !c.getLsbD 55 && !c.getLsbD 68 && !c.getLsbD 81) || (!c.getLsbD 0 && !c.getLsbD 3 && c.getLsbD 52 && !c.getLsbD 55 && !c.getLsbD 68 && !c.getLsbD 81) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 52 && c.getLsbD 55 && !c.getLsbD 68 && !c.getLsbD 81) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 52 && !c.getLsbD 55 && c.getLsbD 68 && !c.getLsbD 81) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 52 && !c.getLsbD 55 && !c.getLsbD 68 && c.getLsbD 81)) &&
   ((c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 53 && !c.getLsbD 54 && !c.getLsbD 67 && !c.getLsbD 78) || (!c.getLsbD 0 && c.getLsbD 3 && !c.getLsbD 53 && !c.getLsbD 54 && !c.getLsbD 67 && !c.getLsbD 78) || (!c.getLsbD 0 && !c.getLsbD 3 && c.getLsbD 53 && !c.getLsbD 54 && !c.getLsbD 67 && !c.getLsbD 78) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 53 && c.getLsbD 54 && !c.getLsbD 67 && !c.getLsbD 78) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 53 && !c.getLsbD 54 && c.getLsbD 67 && !c.getLsbD 78) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 53 && !c.getLsbD 54 && !c.getLsbD 67 && c.getLsbD 78)) &&
   ((c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 53 && !c.getLsbD 55 && !c.getLsbD 66 && !c.getLsbD 79) || (!c.getLsbD 0 && c.getLsbD 3 && !c.getLsbD 53 && !c.getLsbD 55 && !c.getLsbD 66 && !c.getLsbD 79) || (!c.getLsbD 0 && !c.getLsbD 3 && c.getLsbD 53 && !c.getLsbD 55 && !c.getLsbD 66 && !c.getLsbD 79) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 53 && c.getLsbD 55 && !c.getLsbD 66 && !c.getLsbD 79) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 53 && !c.getLsbD 55 && c.getLsbD 66 && !c.getLsbD 79) || (!c.getLsbD 0 && !c.getLsbD 3 && !c.getLsbD 53 && !c.getLsbD 55 && !c.getLsbD 66 && c.getLsbD 79)) &&
   ((c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 46 && !c.getLsbD 56 && !c.getLsbD 65 && !c.getLsbD 75) || (!c.getLsbD 0 && c.getLsbD 4 && !c.getLsbD 46 && !c.getLsbD 56 && !c.getLsbD 65 && !c.getLsbD 75) || (!c.getLsbD 0 && !c.getLsbD 4 && c.getLsbD 46 && !c.getLsbD 56 && !c.getLsbD 65 && !c.getLsbD 75) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 46 && c.getLsbD 56 && !c.getLsbD 65 && !c.getLsbD 75) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 46 && !c.getLsbD 56 && c.getLsbD 65 && !c.getLsbD 75) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 46 && !c.getLsbD 56 && !c.getLsbD 65 && c.getLsbD 75)) &&
   ((c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 46 && !c.getLsbD 57 && !c.getLsbD 64 && !c.getLsbD 74) || (!c.getLsbD 0 && c.getLsbD 4 && !c.getLsbD 46 && !c.getLsbD 57 && !c.getLsbD 64 && !c.getLsbD 74) || (!c.getLsbD 0 && !c.getLsbD 4 && c.getLsbD 46 && !c.getLsbD 57 && !c.getLsbD 64 && !c.getLsbD 74) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 46 && c.getLsbD 57 && !c.getLsbD 64 && !c.getLsbD 74) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 46 && !c.getLsbD 57 && c.getLsbD 64 && !c.getLsbD 74) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 46 && !c.getLsbD 57 && !c.getLsbD 64 && c.getLsbD 74)) &&
   ((c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 47 && !c.getLsbD 56 && !c.getLsbD 63 && !c.getLsbD 77) || (!c.getLsbD 0 && c.getLsbD 4 && !c.getLsbD 47 && !c.getLsbD 56 && !c.getLsbD 63 && !c.getLsbD 77) || (!c.getLsbD 0 && !c.getLsbD 4 && c.getLsbD 47 && !c.getLsbD 56 && !c.getLsbD 63 && !c.getLsbD 77) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 47 && c.getLsbD 56 && !c.getLsbD 63 && !c.getLsbD 77) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 47 && !c.getLsbD 56 && c.getLsbD 63 && !c.getLsbD 77) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 47 && !c.getLsbD 56 && !c.getLsbD 63 && c.getLsbD 77)) &&
   ((c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 47 && !c.getLsbD 57 && !c.getLsbD 62 && !c.getLsbD 76) || (!c.getLsbD 0 && c.getLsbD 4 && !c.getLsbD 47 && !c.getLsbD 57 && !c.getLsbD 62 && !c.getLsbD 76) || (!c.getLsbD 0 && !c.getLsbD 4 && c.getLsbD 47 && !c.getLsbD 57 && !c.getLsbD 62 && !c.getLsbD 76) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 47 && c.getLsbD 57 && !c.getLsbD 62 && !c.getLsbD 76) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 47 && !c.getLsbD 57 && c.getLsbD 62 && !c.getLsbD 76) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 47 && !c.getLsbD 57 && !c.getLsbD 62 && c.getLsbD 76)) &&
   ((c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 48 && !c.getLsbD 54 && !c.getLsbD 65 && !c.getLsbD 76) || (!c.getLsbD 0 && c.getLsbD 4 && !c.getLsbD 48 && !c.getLsbD 54 && !c.getLsbD 65 && !c.getLsbD 76) || (!c.getLsbD 0 && !c.getLsbD 4 && c.getLsbD 48 && !c.getLsbD 54 && !c.getLsbD 65 && !c.getLsbD 76) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 48 && c.getLsbD 54 && !c.getLsbD 65 && !c.getLsbD 76) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 48 && !c.getLsbD 54 && c.getLsbD 65 && !c.getLsbD 76) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 48 && !c.getLsbD 54 && !c.getLsbD 65 && c.getLsbD 76)) &&
   ((c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 48 && !c.getLsbD 55 && !c.getLsbD 64 && !c.getLsbD 77) || (!c.getLsbD 0 && c.getLsbD 4 && !c.getLsbD 48 && !c.getLsbD 55 && !c.getLsbD 64 && !c.getLsbD 77) || (!c.getLsbD 0 && !c.getLsbD 4 && c.getLsbD 48 && !c.getLsbD 55 && !c.getLsbD 64 && !c.getLsbD 77) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 48 && c.getLsbD 55 && !c.getLsbD 64 && !c.getLsbD 77) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 48 && !c.getLsbD 55 && c.getLsbD 64 && !c.getLsbD 77) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 48 && !c.getLsbD 55 && !c.getLsbD 64 && c.getLsbD 77)) &&
   ((c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 49 && !c.getLsbD 54 && !c.getLsbD 63 && !c.getLsbD 74) || (!c.getLsbD 0 && c.getLsbD 4 && !c.getLsbD 49 && !c.getLsbD 54 && !c.getLsbD 63 && !c.getLsbD 74) || (!c.getLsbD 0 && !c.getLsbD 4 && c.getLsbD 49 && !c.getLsbD 54 && !c.getLsbD 63 && !c.getLsbD 74) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 49 && c.getLsbD 54 && !c.getLsbD 63 && !c.getLsbD 74) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 49 && !c.getLsbD 54 && c.getLsbD 63 && !c.getLsbD 74) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 49 && !c.getLsbD 54 && !c.getLsbD 63 && c.getLsbD 74)) &&
   ((c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 49 && !c.getLsbD 55 && !c.getLsbD 62 && !c.getLsbD 75) || (!c.getLsbD 0 && c.getLsbD 4 && !c.getLsbD 49 && !c.getLsbD 55 && !c.getLsbD 62 && !c.getLsbD 75) || (!c.getLsbD 0 && !c.getLsbD 4 && c.getLsbD 49 && !c.getLsbD 55 && !c.getLsbD 62 && !c.getLsbD 75) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 49 && c.getLsbD 55 && !c.getLsbD 62 && !c.getLsbD 75) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 49 && !c.getLsbD 55 && c.getLsbD 62 && !c.getLsbD 75) || (!c.getLsbD 0 && !c.getLsbD 4 && !c.getLsbD 49 && !c.getLsbD 55 && !c.getLsbD 62 && c.getLsbD 75)) &&
   ((c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 46 && !c.getLsbD 52 && !c.getLsbD 61 && !c.getLsbD 71) || (!c.getLsbD 0 && c.getLsbD 5 && !c.getLsbD 46 && !c.getLsbD 52 && !c.getLsbD 61 && !c.getLsbD 71) || (!c.getLsbD 0 && !c.getLsbD 5 && c.getLsbD 46 && !c.getLsbD 52 && !c.getLsbD 61 && !c.getLsbD 71) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 46 && c.getLsbD 52 && !c.getLsbD 61 && !c.getLsbD 71) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 46 && !c.getLsbD 52 && c.getLsbD 61 && !c.getLsbD 71) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 46 && !c.getLsbD 52 && !c.getLsbD 61 && c.getLsbD 71)) &&
   ((c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 46 && !c.getLsbD 53 && !c.getLsbD 60 && !c.getLsbD 70) || (!c.getLsbD 0 && c.getLsbD 5 && !c.getLsbD 46 && !c.getLsbD 53 && !c.getLsbD 60 && !c.getLsbD 70) || (!c.getLsbD 0 && !c.getLsbD 5 && c.getLsbD 46 && !c.getLsbD 53 && !c.getLsbD 60 && !c.getLsbD 70) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 46 && c.getLsbD 53 && !c.getLsbD 60 && !c.getLsbD 70) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 46 && !c.getLsbD 53 && c.getLsbD 60 && !c.getLsbD 70) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 46 && !c.getLsbD 53 && !c.getLsbD 60 && c.getLsbD 70)) &&
   ((c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 47 && !c.getLsbD 52 && !c.getLsbD 59 && !c.getLsbD 73) || (!c.getLsbD 0 && c.getLsbD 5 && !c.getLsbD 47 && !c.getLsbD 52 && !c.getLsbD 59 && !c.getLsbD 73) || (!c.getLsbD 0 && !c.getLsbD 5 && c.getLsbD 47 && !c.getLsbD 52 && !c.getLsbD 59 && !c.getLsbD 73) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 47 && c.getLsbD 52 && !c.getLsbD 59 && !c.getLsbD 73) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 47 && !c.getLsbD 52 && c.getLsbD 59 && !c.getLsbD 73) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 47 && !c.getLsbD 52 && !c.getLsbD 59 && c.getLsbD 73)) &&
   ((c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 47 && !c.getLsbD 53 && !c.getLsbD 58 && !c.getLsbD 72) || (!c.getLsbD 0 && c.getLsbD 5 && !c.getLsbD 47 && !c.getLsbD 53 && !c.getLsbD 58 && !c.getLsbD 72) || (!c.getLsbD 0 && !c.getLsbD 5 && c.getLsbD 47 && !c.getLsbD 53 && !c.getLsbD 58 && !c.getLsbD 72) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 47 && c.getLsbD 53 && !c.getLsbD 58 && !c.getLsbD 72) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 47 && !c.getLsbD 53 && c.getLsbD 58 && !c.getLsbD 72) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 47 && !c.getLsbD 53 && !c.getLsbD 58 && c.getLsbD 72)) &&
   ((c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 48 && !c.getLsbD 50 && !c.getLsbD 61 && !c.getLsbD 72) || (!c.getLsbD 0 && c.getLsbD 5 && !c.getLsbD 48 && !c.getLsbD 50 && !c.getLsbD 61 && !c.getLsbD 72) || (!c.getLsbD 0 && !c.getLsbD 5 && c.getLsbD 48 && !c.getLsbD 50 && !c.getLsbD 61 && !c.getLsbD 72) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 48 && c.getLsbD 50 && !c.getLsbD 61 && !c.getLsbD 72) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 48 && !c.getLsbD 50 && c.getLsbD 61 && !c.getLsbD 72) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 48 && !c.getLsbD 50 && !c.getLsbD 61 && c.getLsbD 72)) &&
   ((c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 48 && !c.getLsbD 51 && !c.getLsbD 60 && !c.getLsbD 73) || (!c.getLsbD 0 && c.getLsbD 5 && !c.getLsbD 48 && !c.getLsbD 51 && !c.getLsbD 60 && !c.getLsbD 73) || (!c.getLsbD 0 && !c.getLsbD 5 && c.getLsbD 48 && !c.getLsbD 51 && !c.getLsbD 60 && !c.getLsbD 73) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 48 && c.getLsbD 51 && !c.getLsbD 60 && !c.getLsbD 73) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 48 && !c.getLsbD 51 && c.getLsbD 60 && !c.getLsbD 73) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 48 && !c.getLsbD 51 && !c.getLsbD 60 && c.getLsbD 73)) &&
   ((c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 49 && !c.getLsbD 50 && !c.getLsbD 59 && !c.getLsbD 70) || (!c.getLsbD 0 && c.getLsbD 5 && !c.getLsbD 49 && !c.getLsbD 50 && !c.getLsbD 59 && !c.getLsbD 70) || (!c.getLsbD 0 && !c.getLsbD 5 && c.getLsbD 49 && !c.getLsbD 50 && !c.getLsbD 59 && !c.getLsbD 70) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 49 && c.getLsbD 50 && !c.getLsbD 59 && !c.getLsbD 70) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 49 && !c.getLsbD 50 && c.getLsbD 59 && !c.getLsbD 70) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 49 && !c.getLsbD 50 && !c.getLsbD 59 && c.getLsbD 70)) &&
   ((c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 49 && !c.getLsbD 51 && !c.getLsbD 58 && !c.getLsbD 71) || (!c.getLsbD 0 && c.getLsbD 5 && !c.getLsbD 49 && !c.getLsbD 51 && !c.getLsbD 58 && !c.getLsbD 71) || (!c.getLsbD 0 && !c.getLsbD 5 && c.getLsbD 49 && !c.getLsbD 51 && !c.getLsbD 58 && !c.getLsbD 71) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 49 && c.getLsbD 51 && !c.getLsbD 58 && !c.getLsbD 71) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 49 && !c.getLsbD 51 && c.getLsbD 58 && !c.getLsbD 71) || (!c.getLsbD 0 && !c.getLsbD 5 && !c.getLsbD 49 && !c.getLsbD 51 && !c.getLsbD 58 && c.getLsbD 71)) &&
   ((c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 34 && !c.getLsbD 40 && !c.getLsbD 45 && !c.getLsbD 83) || (!c.getLsbD 1 && c.getLsbD 2 && !c.getLsbD 34 && !c.getLsbD 40 && !c.getLsbD 45 && !c.getLsbD 83) || (!c.getLsbD 1 && !c.getLsbD 2 && c.getLsbD 34 && !c.getLsbD 40 && !c.getLsbD 45 && !c.getLsbD 83) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 34 && c.getLsbD 40 && !c.getLsbD 45 && !c.getLsbD 83) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 34 && !c.getLsbD 40 && c.getLsbD 45 && !c.getLsbD 83) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 34 && !c.getLsbD 40 && !c.getLsbD 45 && c.getLsbD 83)) &&
   ((c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 34 && !c.getLsbD 41 && !c.getLsbD 44 && !c.getLsbD 82) || (!c.getLsbD 1 && c.getLsbD 2 && !c.getLsbD 34 && !c.getLsbD 41 && !c.getLsbD 44 && !c.getLsbD 82) || (!c.getLsbD 1 && !c.getLsbD 2 && c.getLsbD 34 && !c.getLsbD 41 && !c.getLsbD 44 && !c.getLsbD 82) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 34 && c.getLsbD 41 && !c.getLsbD 44 && !c.getLsbD 82) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 34 && !c.getLsbD 41 && c.getLsbD 44 && !c.getLsbD 82) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 34 && !c.getLsbD 41 && !c.getLsbD 44 && c.getLsbD 82)) &&
   ((c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 35 && !c.getLsbD 40 && !c.getLsbD 43 && !c.getLsbD 85) || (!c.getLsbD 1 && c.getLsbD 2 && !c.getLsbD 35 && !c.getLsbD 40 && !c.getLsbD 43 && !c.getLsbD 85) || (!c.getLsbD 1 && !c.getLsbD 2 && c.getLsbD 35 && !c.getLsbD 40 && !c.getLsbD 43 && !c.getLsbD 85) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 35 && c.getLsbD 40 && !c.getLsbD 43 && !c.getLsbD 85) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 35 && !c.getLsbD 40 && c.getLsbD 43 && !c.getLsbD 85) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 35 && !c.getLsbD 40 && !c.getLsbD 43 && c.getLsbD 85)) &&
   ((c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 35 && !c.getLsbD 41 && !c.getLsbD 42 && !c.getLsbD 84) || (!c.getLsbD 1 && c.getLsbD 2 && !c.getLsbD 35 && !c.getLsbD 41 && !c.getLsbD 42 && !c.getLsbD 84) || (!c.getLsbD 1 && !c.getLsbD 2 && c.getLsbD 35 && !c.getLsbD 41 && !c.getLsbD 42 && !c.getLsbD 84) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 35 && c.getLsbD 41 && !c.getLsbD 42 && !c.getLsbD 84) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 35 && !c.getLsbD 41 && c.getLsbD 42 && !c.getLsbD 84) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 35 && !c.getLsbD 41 && !c.getLsbD 42 && c.getLsbD 84)) &&
   ((c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 36 && !c.getLsbD 38 && !c.getLsbD 45 && !c.getLsbD 84) || (!c.getLsbD 1 && c.getLsbD 2 && !c.getLsbD 36 && !c.getLsbD 38 && !c.getLsbD 45 && !c.getLsbD 84) || (!c.getLsbD 1 && !c.getLsbD 2 && c.getLsbD 36 && !c.getLsbD 38 && !c.getLsbD 45 && !c.getLsbD 84) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 36 && c.getLsbD 38 && !c.getLsbD 45 && !c.getLsbD 84) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 36 && !c.getLsbD 38 && c.getLsbD 45 && !c.getLsbD 84) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 36 && !c.getLsbD 38 && !c.getLsbD 45 && c.getLsbD 84)) &&
   ((c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 36 && !c.getLsbD 39 && !c.getLsbD 44 && !c.getLsbD 85) || (!c.getLsbD 1 && c.getLsbD 2 && !c.getLsbD 36 && !c.getLsbD 39 && !c.getLsbD 44 && !c.getLsbD 85) || (!c.getLsbD 1 && !c.getLsbD 2 && c.getLsbD 36 && !c.getLsbD 39 && !c.getLsbD 44 && !c.getLsbD 85) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 36 && c.getLsbD 39 && !c.getLsbD 44 && !c.getLsbD 85) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 36 && !c.getLsbD 39 && c.getLsbD 44 && !c.getLsbD 85) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 36 && !c.getLsbD 39 && !c.getLsbD 44 && c.getLsbD 85)) &&
   ((c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 37 && !c.getLsbD 38 && !c.getLsbD 43 && !c.getLsbD 82) || (!c.getLsbD 1 && c.getLsbD 2 && !c.getLsbD 37 && !c.getLsbD 38 && !c.getLsbD 43 && !c.getLsbD 82) || (!c.getLsbD 1 && !c.getLsbD 2 && c.getLsbD 37 && !c.getLsbD 38 && !c.getLsbD 43 && !c.getLsbD 82) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 37 && c.getLsbD 38 && !c.getLsbD 43 && !c.getLsbD 82) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 37 && !c.getLsbD 38 && c.getLsbD 43 && !c.getLsbD 82) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 37 && !c.getLsbD 38 && !c.getLsbD 43 && c.getLsbD 82)) &&
   ((c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 37 && !c.getLsbD 39 && !c.getLsbD 42 && !c.getLsbD 83) || (!c.getLsbD 1 && c.getLsbD 2 && !c.getLsbD 37 && !c.getLsbD 39 && !c.getLsbD 42 && !c.getLsbD 83) || (!c.getLsbD 1 && !c.getLsbD 2 && c.getLsbD 37 && !c.getLsbD 39 && !c.getLsbD 42 && !c.getLsbD 83) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 37 && c.getLsbD 39 && !c.getLsbD 42 && !c.getLsbD 83) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 37 && !c.getLsbD 39 && c.getLsbD 42 && !c.getLsbD 83) || (!c.getLsbD 1 && !c.getLsbD 2 && !c.getLsbD 37 && !c.getLsbD 39 && !c.getLsbD 42 && c.getLsbD 83)) &&
   ((c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 26 && !c.getLsbD 32 && !c.getLsbD 45 && !c.getLsbD 79) || (!c.getLsbD 1 && c.getLsbD 3 && !c.getLsbD 26 && !c.getLsbD 32 && !c.getLsbD 45 && !c.getLsbD 79) || (!c.getLsbD 1 && !c.getLsbD 3 && c.getLsbD 26 && !c.getLsbD 32 && !c.getLsbD 45 && !c.getLsbD 79) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 26 && c.getLsbD 32 && !c.getLsbD 45 && !c.getLsbD 79) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 26 && !c.getLsbD 32 && c.getLsbD 45 && !c.getLsbD 79) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 26 && !c.getLsbD 32 && !c.getLsbD 45 && c.getLsbD 79)) &&
   ((c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 26 && !c.getLsbD 33 && !c.getLsbD 44 && !c.getLsbD 78) || (!c.getLsbD 1 && c.getLsbD 3 && !c.getLsbD 26 && !c.getLsbD 33 && !c.getLsbD 44 && !c.getLsbD 78) || (!c.getLsbD 1 && !c.getLsbD 3 && c.getLsbD 26 && !c.getLsbD 33 && !c.getLsbD 44 && !c.getLsbD 78) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 26 && c.getLsbD 33 && !c.getLsbD 44 && !c.getLsbD 78) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 26 && !c.getLsbD 33 && c.getLsbD 44 && !c.getLsbD 78) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 26 && !c.getLsbD 33 && !c.getLsbD 44 && c.getLsbD 78)) &&
   ((c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 27 && !c.getLsbD 32 && !c.getLsbD 43 && !c.getLsbD 81) || (!c.getLsbD 1 && c.getLsbD 3 && !c.getLsbD 27 && !c.getLsbD 32 && !c.getLsbD 43 && !c.getLsbD 81) || (!c.getLsbD 1 && !c.getLsbD 3 && c.getLsbD 27 && !c.getLsbD 32 && !c.getLsbD 43 && !c.getLsbD 81) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 27 && c.getLsbD 32 && !c.getLsbD 43 && !c.getLsbD 81) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 27 && !c.getLsbD 32 && c.getLsbD 43 && !c.getLsbD 81) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 27 && !c.getLsbD 32 && !c.getLsbD 43 && c.getLsbD 81)) &&
   ((c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 27 && !c.getLsbD 33 && !c.getLsbD 42 && !c.getLsbD 80) || (!c.getLsbD 1 && c.getLsbD 3 && !c.getLsbD 27 && !c.getLsbD 33 && !c.getLsbD 42 && !c.getLsbD 80) || (!c.getLsbD 1 && !c.getLsbD 3 && c.getLsbD 27 && !c.getLsbD 33 && !c.getLsbD 42 && !c.getLsbD 80) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 27 && c.getLsbD 33 && !c.getLsbD 42 && !c.getLsbD 80) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 27 && !c.getLsbD 33 && c.getLsbD 42 && !c.getLsbD 80) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 27 && !c.getLsbD 33 && !c.getLsbD 42 && c.getLsbD 80)) &&
   ((c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 28 && !c.getLsbD 30 && !c.getLsbD 45 && !c.getLsbD 80) || (!c.getLsbD 1 && c.getLsbD 3 && !c.getLsbD 28 && !c.getLsbD 30 && !c.getLsbD 45 && !c.getLsbD 80) || (!c.getLsbD 1 && !c.getLsbD 3 && c.getLsbD 28 && !c.getLsbD 30 && !c.getLsbD 45 && !c.getLsbD 80) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 28 && c.getLsbD 30 && !c.getLsbD 45 && !c.getLsbD 80) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 28 && !c.getLsbD 30 && c.getLsbD 45 && !c.getLsbD 80) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 28 && !c.getLsbD 30 && !c.getLsbD 45 && c.getLsbD 80)) &&
   ((c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 28 && !c.getLsbD 31 && !c.getLsbD 44 && !c.getLsbD 81) || (!c.getLsbD 1 && c.getLsbD 3 && !c.getLsbD 28 && !c.getLsbD 31 && !c.getLsbD 44 && !c.getLsbD 81) || (!c.getLsbD 1 && !c.getLsbD 3 && c.getLsbD 28 && !c.getLsbD 31 && !c.getLsbD 44 && !c.getLsbD 81) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 28 && c.getLsbD 31 && !c.getLsbD 44 && !c.getLsbD 81) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 28 && !c.getLsbD 31 && c.getLsbD 44 && !c.getLsbD 81) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 28 && !c.getLsbD 31 && !c.getLsbD 44 && c.getLsbD 81)) &&
   ((c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 29 && !c.getLsbD 30 && !c.getLsbD 43 && !c.getLsbD 78) || (!c.getLsbD 1 && c.getLsbD 3 && !c.getLsbD 29 && !c.getLsbD 30 && !c.getLsbD 43 && !c.getLsbD 78) || (!c.getLsbD 1 && !c.getLsbD 3 && c.getLsbD 29 && !c.getLsbD 30 && !c.getLsbD 43 && !c.getLsbD 78) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 29 && c.getLsbD 30 && !c.getLsbD 43 && !c.getLsbD 78) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 29 && !c.getLsbD 30 && c.getLsbD 43 && !c.getLsbD 78) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 29 && !c.getLsbD 30 && !c.getLsbD 43 && c.getLsbD 78)) &&
   ((c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 29 && !c.getLsbD 31 && !c.getLsbD 42 && !c.getLsbD 79) || (!c.getLsbD 1 && c.getLsbD 3 && !c.getLsbD 29 && !c.getLsbD 31 && !c.getLsbD 42 && !c.getLsbD 79) || (!c.getLsbD 1 && !c.getLsbD 3 && c.getLsbD 29 && !c.getLsbD 31 && !c.getLsbD 42 && !c.getLsbD 79) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 29 && c.getLsbD 31 && !c.getLsbD 42 && !c.getLsbD 79) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 29 && !c.getLsbD 31 && c.getLsbD 42 && !c.getLsbD 79) || (!c.getLsbD 1 && !c.getLsbD 3 && !c.getLsbD 29 && !c.getLsbD 31 && !c.getLsbD 42 && c.getLsbD 79)) &&
   ((c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 22 && !c.getLsbD 32 && !c.getLsbD 41 && !c.getLsbD 75) || (!c.getLsbD 1 && c.getLsbD 4 && !c.getLsbD 22 && !c.getLsbD 32 && !c.getLsbD 41 && !c.getLsbD 75) || (!c.getLsbD 1 && !c.getLsbD 4 && c.getLsbD 22 && !c.getLsbD 32 && !c.getLsbD 41 && !c.getLsbD 75) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 22 && c.getLsbD 32 && !c.getLsbD 41 && !c.getLsbD 75) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 22 && !c.getLsbD 32 && c.getLsbD 41 && !c.getLsbD 75) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 22 && !c.getLsbD 32 && !c.getLsbD 41 && c.getLsbD 75)) &&
   ((c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 22 && !c.getLsbD 33 && !c.getLsbD 40 && !c.getLsbD 74) || (!c.getLsbD 1 && c.getLsbD 4 && !c.getLsbD 22 && !c.getLsbD 33 && !c.getLsbD 40 && !c.getLsbD 74) || (!c.getLsbD 1 && !c.getLsbD 4 && c.getLsbD 22 && !c.getLsbD 33 && !c.getLsbD 40 && !c.getLsbD 74) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 22 && c.getLsbD 33 && !c.getLsbD 40 && !c.getLsbD 74) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 22 && !c.getLsbD 33 && c.getLsbD 40 && !c.getLsbD 74) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 22 && !c.getLsbD 33 && !c.getLsbD 40 && c.getLsbD 74)) &&
   ((c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 23 && !c.getLsbD 32 && !c.getLsbD 39 && !c.getLsbD 77) || (!c.getLsbD 1 && c.getLsbD 4 && !c.getLsbD 23 && !c.getLsbD 32 && !c.getLsbD 39 && !c.getLsbD 77) || (!c.getLsbD 1 && !c.getLsbD 4 && c.getLsbD 23 && !c.getLsbD 32 && !c.getLsbD 39 && !c.getLsbD 77) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 23 && c.getLsbD 32 && !c.getLsbD 39 && !c.getLsbD 77) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 23 && !c.getLsbD 32 && c.getLsbD 39 && !c.getLsbD 77) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 23 && !c.getLsbD 32 && !c.getLsbD 39 && c.getLsbD 77)) &&
   ((c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 23 && !c.getLsbD 33 && !c.getLsbD 38 && !c.getLsbD 76) || (!c.getLsbD 1 && c.getLsbD 4 && !c.getLsbD 23 && !c.getLsbD 33 && !c.getLsbD 38 && !c.getLsbD 76) || (!c.getLsbD 1 && !c.getLsbD 4 && c.getLsbD 23 && !c.getLsbD 33 && !c.getLsbD 38 && !c.getLsbD 76) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 23 && c.getLsbD 33 && !c.getLsbD 38 && !c.getLsbD 76) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 23 && !c.getLsbD 33 && c.getLsbD 38 && !c.getLsbD 76) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 23 && !c.getLsbD 33 && !c.getLsbD 38 && c.getLsbD 76)) &&
   ((c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 24 && !c.getLsbD 30 && !c.getLsbD 41 && !c.getLsbD 76) || (!c.getLsbD 1 && c.getLsbD 4 && !c.getLsbD 24 && !c.getLsbD 30 && !c.getLsbD 41 && !c.getLsbD 76) || (!c.getLsbD 1 && !c.getLsbD 4 && c.getLsbD 24 && !c.getLsbD 30 && !c.getLsbD 41 && !c.getLsbD 76) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 24 && c.getLsbD 30 && !c.getLsbD 41 && !c.getLsbD 76) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 24 && !c.getLsbD 30 && c.getLsbD 41 && !c.getLsbD 76) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 24 && !c.getLsbD 30 && !c.getLsbD 41 && c.getLsbD 76)) &&
   ((c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 24 && !c.getLsbD 31 && !c.getLsbD 40 && !c.getLsbD 77) || (!c.getLsbD 1 && c.getLsbD 4 && !c.getLsbD 24 && !c.getLsbD 31 && !c.getLsbD 40 && !c.getLsbD 77) || (!c.getLsbD 1 && !c.getLsbD 4 && c.getLsbD 24 && !c.getLsbD 31 && !c.getLsbD 40 && !c.getLsbD 77) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 24 && c.getLsbD 31 && !c.getLsbD 40 && !c.getLsbD 77) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 24 && !c.getLsbD 31 && c.getLsbD 40 && !c.getLsbD 77) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 24 && !c.getLsbD 31 && !c.getLsbD 40 && c.getLsbD 77)) &&
   ((c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 25 && !c.getLsbD 30 && !c.getLsbD 39 && !c.getLsbD 74) || (!c.getLsbD 1 && c.getLsbD 4 && !c.getLsbD 25 && !c.getLsbD 30 && !c.getLsbD 39 && !c.getLsbD 74) || (!c.getLsbD 1 && !c.getLsbD 4 && c.getLsbD 25 && !c.getLsbD 30 && !c.getLsbD 39 && !c.getLsbD 74) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 25 && c.getLsbD 30 && !c.getLsbD 39 && !c.getLsbD 74) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 25 && !c.getLsbD 30 && c.getLsbD 39 && !c.getLsbD 74) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 25 && !c.getLsbD 30 && !c.getLsbD 39 && c.getLsbD 74)) &&
   ((c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 25 && !c.getLsbD 31 && !c.getLsbD 38 && !c.getLsbD 75) || (!c.getLsbD 1 && c.getLsbD 4 && !c.getLsbD 25 && !c.getLsbD 31 && !c.getLsbD 38 && !c.getLsbD 75) || (!c.getLsbD 1 && !c.getLsbD 4 && c.getLsbD 25 && !c.getLsbD 31 && !c.getLsbD 38 && !c.getLsbD 75) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 25 && c.getLsbD 31 && !c.getLsbD 38 && !c.getLsbD 75) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 25 && !c.getLsbD 31 && c.getLsbD 38 && !c.getLsbD 75) || (!c.getLsbD 1 && !c.getLsbD 4 && !c.getLsbD 25 && !c.getLsbD 31 && !c.getLsbD 38 && c.getLsbD 75)) &&
   ((c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 22 && !c.getLsbD 28 && !c.getLsbD 37 && !c.getLsbD 71) || (!c.getLsbD 1 && c.getLsbD 5 && !c.getLsbD 22 && !c.getLsbD 28 && !c.getLsbD 37 && !c.getLsbD 71) || (!c.getLsbD 1 && !c.getLsbD 5 && c.getLsbD 22 && !c.getLsbD 28 && !c.getLsbD 37 && !c.getLsbD 71) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 22 && c.getLsbD 28 && !c.getLsbD 37 && !c.getLsbD 71) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 22 && !c.getLsbD 28 && c.getLsbD 37 && !c.getLsbD 71) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 22 && !c.getLsbD 28 && !c.getLsbD 37 && c.getLsbD 71)) &&
   ((c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 22 && !c.getLsbD 29 && !c.getLsbD 36 && !c.getLsbD 70) || (!c.getLsbD 1 && c.getLsbD 5 && !c.getLsbD 22 && !c.getLsbD 29 && !c.getLsbD 36 && !c.getLsbD 70) || (!c.getLsbD 1 && !c.getLsbD 5 && c.getLsbD 22 && !c.getLsbD 29 && !c.getLsbD 36 && !c.getLsbD 70) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 22 && c.getLsbD 29 && !c.getLsbD 36 && !c.getLsbD 70) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 22 && !c.getLsbD 29 && c.getLsbD 36 && !c.getLsbD 70) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 22 && !c.getLsbD 29 && !c.getLsbD 36 && c.getLsbD 70)) &&
   ((c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 23 && !c.getLsbD 28 && !c.getLsbD 35 && !c.getLsbD 73) || (!c.getLsbD 1 && c.getLsbD 5 && !c.getLsbD 23 && !c.getLsbD 28 && !c.getLsbD 35 && !c.getLsbD 73) || (!c.getLsbD 1 && !c.getLsbD 5 && c.getLsbD 23 && !c.getLsbD 28 && !c.getLsbD 35 && !c.getLsbD 73) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 23 && c.getLsbD 28 && !c.getLsbD 35 && !c.getLsbD 73) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 23 && !c.getLsbD 28 && c.getLsbD 35 && !c.getLsbD 73) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 23 && !c.getLsbD 28 && !c.getLsbD 35 && c.getLsbD 73)) &&
   ((c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 23 && !c.getLsbD 29 && !c.getLsbD 34 && !c.getLsbD 72) || (!c.getLsbD 1 && c.getLsbD 5 && !c.getLsbD 23 && !c.getLsbD 29 && !c.getLsbD 34 && !c.getLsbD 72) || (!c.getLsbD 1 && !c.getLsbD 5 && c.getLsbD 23 && !c.getLsbD 29 && !c.getLsbD 34 && !c.getLsbD 72) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 23 && c.getLsbD 29 && !c.getLsbD 34 && !c.getLsbD 72) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 23 && !c.getLsbD 29 && c.getLsbD 34 && !c.getLsbD 72) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 23 && !c.getLsbD 29 && !c.getLsbD 34 && c.getLsbD 72)) &&
   ((c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 24 && !c.getLsbD 26 && !c.getLsbD 37 && !c.getLsbD 72) || (!c.getLsbD 1 && c.getLsbD 5 && !c.getLsbD 24 && !c.getLsbD 26 && !c.getLsbD 37 && !c.getLsbD 72) || (!c.getLsbD 1 && !c.getLsbD 5 && c.getLsbD 24 && !c.getLsbD 26 && !c.getLsbD 37 && !c.getLsbD 72) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 24 && c.getLsbD 26 && !c.getLsbD 37 && !c.getLsbD 72) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 24 && !c.getLsbD 26 && c.getLsbD 37 && !c.getLsbD 72) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 24 && !c.getLsbD 26 && !c.getLsbD 37 && c.getLsbD 72)) &&
   ((c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 24 && !c.getLsbD 27 && !c.getLsbD 36 && !c.getLsbD 73) || (!c.getLsbD 1 && c.getLsbD 5 && !c.getLsbD 24 && !c.getLsbD 27 && !c.getLsbD 36 && !c.getLsbD 73) || (!c.getLsbD 1 && !c.getLsbD 5 && c.getLsbD 24 && !c.getLsbD 27 && !c.getLsbD 36 && !c.getLsbD 73) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 24 && c.getLsbD 27 && !c.getLsbD 36 && !c.getLsbD 73) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 24 && !c.getLsbD 27 && c.getLsbD 36 && !c.getLsbD 73) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 24 && !c.getLsbD 27 && !c.getLsbD 36 && c.getLsbD 73)) &&
   ((c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 25 && !c.getLsbD 26 && !c.getLsbD 35 && !c.getLsbD 70) || (!c.getLsbD 1 && c.getLsbD 5 && !c.getLsbD 25 && !c.getLsbD 26 && !c.getLsbD 35 && !c.getLsbD 70) || (!c.getLsbD 1 && !c.getLsbD 5 && c.getLsbD 25 && !c.getLsbD 26 && !c.getLsbD 35 && !c.getLsbD 70) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 25 && c.getLsbD 26 && !c.getLsbD 35 && !c.getLsbD 70) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 25 && !c.getLsbD 26 && c.getLsbD 35 && !c.getLsbD 70) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 25 && !c.getLsbD 26 && !c.getLsbD 35 && c.getLsbD 70)) &&
   ((c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 25 && !c.getLsbD 27 && !c.getLsbD 34 && !c.getLsbD 71) || (!c.getLsbD 1 && c.getLsbD 5 && !c.getLsbD 25 && !c.getLsbD 27 && !c.getLsbD 34 && !c.getLsbD 71) || (!c.getLsbD 1 && !c.getLsbD 5 && c.getLsbD 25 && !c.getLsbD 27 && !c.getLsbD 34 && !c.getLsbD 71) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 25 && c.getLsbD 27 && !c.getLsbD 34 && !c.getLsbD 71) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 25 && !c.getLsbD 27 && c.getLsbD 34 && !c.getLsbD 71) || (!c.getLsbD 1 && !c.getLsbD 5 && !c.getLsbD 25 && !c.getLsbD 27 && !c.getLsbD 34 && c.getLsbD 71)) &&
   ((c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 14 && !c.getLsbD 20 && !c.getLsbD 45 && !c.getLsbD 67) || (!c.getLsbD 2 && c.getLsbD 3 && !c.getLsbD 14 && !c.getLsbD 20 && !c.getLsbD 45 && !c.getLsbD 67) || (!c.getLsbD 2 && !c.getLsbD 3 && c.getLsbD 14 && !c.getLsbD 20 && !c.getLsbD 45 && !c.getLsbD 67) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 14 && c.getLsbD 20 && !c.getLsbD 45 && !c.getLsbD 67) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 14 && !c.getLsbD 20 && c.getLsbD 45 && !c.getLsbD 67) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 14 && !c.getLsbD 20 && !c.getLsbD 45 && c.getLsbD 67)) &&
   ((c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 14 && !c.getLsbD 21 && !c.getLsbD 44 && !c.getLsbD 66) || (!c.getLsbD 2 && c.getLsbD 3 && !c.getLsbD 14 && !c.getLsbD 21 && !c.getLsbD 44 && !c.getLsbD 66) || (!c.getLsbD 2 && !c.getLsbD 3 && c.getLsbD 14 && !c.getLsbD 21 && !c.getLsbD 44 && !c.getLsbD 66) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 14 && c.getLsbD 21 && !c.getLsbD 44 && !c.getLsbD 66) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 14 && !c.getLsbD 21 && c.getLsbD 44 && !c.getLsbD 66) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 14 && !c.getLsbD 21 && !c.getLsbD 44 && c.getLsbD 66)) &&
   ((c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 15 && !c.getLsbD 20 && !c.getLsbD 43 && !c.getLsbD 69) || (!c.getLsbD 2 && c.getLsbD 3 && !c.getLsbD 15 && !c.getLsbD 20 && !c.getLsbD 43 && !c.getLsbD 69) || (!c.getLsbD 2 && !c.getLsbD 3 && c.getLsbD 15 && !c.getLsbD 20 && !c.getLsbD 43 && !c.getLsbD 69) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 15 && c.getLsbD 20 && !c.getLsbD 43 && !c.getLsbD 69) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 15 && !c.getLsbD 20 && c.getLsbD 43 && !c.getLsbD 69) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 15 && !c.getLsbD 20 && !c.getLsbD 43 && c.getLsbD 69)) &&
   ((c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 15 && !c.getLsbD 21 && !c.getLsbD 42 && !c.getLsbD 68) || (!c.getLsbD 2 && c.getLsbD 3 && !c.getLsbD 15 && !c.getLsbD 21 && !c.getLsbD 42 && !c.getLsbD 68) || (!c.getLsbD 2 && !c.getLsbD 3 && c.getLsbD 15 && !c.getLsbD 21 && !c.getLsbD 42 && !c.getLsbD 68) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 15 && c.getLsbD 21 && !c.getLsbD 42 && !c.getLsbD 68) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 15 && !c.getLsbD 21 && c.getLsbD 42 && !c.getLsbD 68) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 15 && !c.getLsbD 21 && !c.getLsbD 42 && c.getLsbD 68)) &&
   ((c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 16 && !c.getLsbD 18 && !c.getLsbD 45 && !c.getLsbD 68) || (!c.getLsbD 2 && c.getLsbD 3 && !c.getLsbD 16 && !c.getLsbD 18 && !c.getLsbD 45 && !c.getLsbD 68) || (!c.getLsbD 2 && !c.getLsbD 3 && c.getLsbD 16 && !c.getLsbD 18 && !c.getLsbD 45 && !c.getLsbD 68) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 16 && c.getLsbD 18 && !c.getLsbD 45 && !c.getLsbD 68) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 16 && !c.getLsbD 18 && c.getLsbD 45 && !c.getLsbD 68) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 16 && !c.getLsbD 18 && !c.getLsbD 45 && c.getLsbD 68)) &&
   ((c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 16 && !c.getLsbD 19 && !c.getLsbD 44 && !c.getLsbD 69) || (!c.getLsbD 2 && c.getLsbD 3 && !c.getLsbD 16 && !c.getLsbD 19 && !c.getLsbD 44 && !c.getLsbD 69) || (!c.getLsbD 2 && !c.getLsbD 3 && c.getLsbD 16 && !c.getLsbD 19 && !c.getLsbD 44 && !c.getLsbD 69) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 16 && c.getLsbD 19 && !c.getLsbD 44 && !c.getLsbD 69) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 16 && !c.getLsbD 19 && c.getLsbD 44 && !c.getLsbD 69) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 16 && !c.getLsbD 19 && !c.getLsbD 44 && c.getLsbD 69)) &&
   ((c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 17 && !c.getLsbD 18 && !c.getLsbD 43 && !c.getLsbD 66) || (!c.getLsbD 2 && c.getLsbD 3 && !c.getLsbD 17 && !c.getLsbD 18 && !c.getLsbD 43 && !c.getLsbD 66) || (!c.getLsbD 2 && !c.getLsbD 3 && c.getLsbD 17 && !c.getLsbD 18 && !c.getLsbD 43 && !c.getLsbD 66) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 17 && c.getLsbD 18 && !c.getLsbD 43 && !c.getLsbD 66) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 17 && !c.getLsbD 18 && c.getLsbD 43 && !c.getLsbD 66) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 17 && !c.getLsbD 18 && !c.getLsbD 43 && c.getLsbD 66)) &&
   ((c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 17 && !c.getLsbD 19 && !c.getLsbD 42 && !c.getLsbD 67) || (!c.getLsbD 2 && c.getLsbD 3 && !c.getLsbD 17 && !c.getLsbD 19 && !c.getLsbD 42 && !c.getLsbD 67) || (!c.getLsbD 2 && !c.getLsbD 3 && c.getLsbD 17 && !c.getLsbD 19 && !c.getLsbD 42 && !c.getLsbD 67) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 17 && c.getLsbD 19 && !c.getLsbD 42 && !c.getLsbD 67) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 17 && !c.getLsbD 19 && c.getLsbD 42 && !c.getLsbD 67) || (!c.getLsbD 2 && !c.getLsbD 3 && !c.getLsbD 17 && !c.getLsbD 19 && !c.getLsbD 42 && c.getLsbD 67)) &&
   ((c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 10 && !c.getLsbD 20 && !c.getLsbD 41 && !c.getLsbD 63) || (!c.getLsbD 2 && c.getLsbD 4 && !c.getLsbD 10 && !c.getLsbD 20 && !c.getLsbD 41 && !c.getLsbD 63) || (!c.getLsbD 2 && !c.getLsbD 4 && c.getLsbD 10 && !c.getLsbD 20 && !c.getLsbD 41 && !c.getLsbD 63) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 10 && c.getLsbD 20 && !c.getLsbD 41 && !c.getLsbD 63) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 10 && !c.getLsbD 20 && c.getLsbD 41 && !c.getLsbD 63) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 10 && !c.getLsbD 20 && !c.getLsbD 41 && c.getLsbD 63)) &&
   ((c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 10 && !c.getLsbD 21 && !c.getLsbD 40 && !c.getLsbD 62) || (!c.getLsbD 2 && c.getLsbD 4 && !c.getLsbD 10 && !c.getLsbD 21 && !c.getLsbD 40 && !c.getLsbD 62) || (!c.getLsbD 2 && !c.getLsbD 4 && c.getLsbD 10 && !c.getLsbD 21 && !c.getLsbD 40 && !c.getLsbD 62) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 10 && c.getLsbD 21 && !c.getLsbD 40 && !c.getLsbD 62) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 10 && !c.getLsbD 21 && c.getLsbD 40 && !c.getLsbD 62) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 10 && !c.getLsbD 21 && !c.getLsbD 40 && c.getLsbD 62)) &&
   ((c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 11 && !c.getLsbD 20 && !c.getLsbD 39 && !c.getLsbD 65) || (!c.getLsbD 2 && c.getLsbD 4 && !c.getLsbD 11 && !c.getLsbD 20 && !c.getLsbD 39 && !c.getLsbD 65) || (!c.getLsbD 2 && !c.getLsbD 4 && c.getLsbD 11 && !c.getLsbD 20 && !c.getLsbD 39 && !c.getLsbD 65) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 11 && c.getLsbD 20 && !c.getLsbD 39 && !c.getLsbD 65) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 11 && !c.getLsbD 20 && c.getLsbD 39 && !c.getLsbD 65) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 11 && !c.getLsbD 20 && !c.getLsbD 39 && c.getLsbD 65)) &&
   ((c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 11 && !c.getLsbD 21 && !c.getLsbD 38 && !c.getLsbD 64) || (!c.getLsbD 2 && c.getLsbD 4 && !c.getLsbD 11 && !c.getLsbD 21 && !c.getLsbD 38 && !c.getLsbD 64) || (!c.getLsbD 2 && !c.getLsbD 4 && c.getLsbD 11 && !c.getLsbD 21 && !c.getLsbD 38 && !c.getLsbD 64) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 11 && c.getLsbD 21 && !c.getLsbD 38 && !c.getLsbD 64) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 11 && !c.getLsbD 21 && c.getLsbD 38 && !c.getLsbD 64) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 11 && !c.getLsbD 21 && !c.getLsbD 38 && c.getLsbD 64)) &&
   ((c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 12 && !c.getLsbD 18 && !c.getLsbD 41 && !c.getLsbD 64) || (!c.getLsbD 2 && c.getLsbD 4 && !c.getLsbD 12 && !c.getLsbD 18 && !c.getLsbD 41 && !c.getLsbD 64) || (!c.getLsbD 2 && !c.getLsbD 4 && c.getLsbD 12 && !c.getLsbD 18 && !c.getLsbD 41 && !c.getLsbD 64) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 12 && c.getLsbD 18 && !c.getLsbD 41 && !c.getLsbD 64) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 12 && !c.getLsbD 18 && c.getLsbD 41 && !c.getLsbD 64) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 12 && !c.getLsbD 18 && !c.getLsbD 41 && c.getLsbD 64)) &&
   ((c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 12 && !c.getLsbD 19 && !c.getLsbD 40 && !c.getLsbD 65) || (!c.getLsbD 2 && c.getLsbD 4 && !c.getLsbD 12 && !c.getLsbD 19 && !c.getLsbD 40 && !c.getLsbD 65) || (!c.getLsbD 2 && !c.getLsbD 4 && c.getLsbD 12 && !c.getLsbD 19 && !c.getLsbD 40 && !c.getLsbD 65) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 12 && c.getLsbD 19 && !c.getLsbD 40 && !c.getLsbD 65) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 12 && !c.getLsbD 19 && c.getLsbD 40 && !c.getLsbD 65) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 12 && !c.getLsbD 19 && !c.getLsbD 40 && c.getLsbD 65)) &&
   ((c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 13 && !c.getLsbD 18 && !c.getLsbD 39 && !c.getLsbD 62) || (!c.getLsbD 2 && c.getLsbD 4 && !c.getLsbD 13 && !c.getLsbD 18 && !c.getLsbD 39 && !c.getLsbD 62) || (!c.getLsbD 2 && !c.getLsbD 4 && c.getLsbD 13 && !c.getLsbD 18 && !c.getLsbD 39 && !c.getLsbD 62) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 13 && c.getLsbD 18 && !c.getLsbD 39 && !c.getLsbD 62) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 13 && !c.getLsbD 18 && c.getLsbD 39 && !c.getLsbD 62) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 13 && !c.getLsbD 18 && !c.getLsbD 39 && c.getLsbD 62)) &&
   ((c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 13 && !c.getLsbD 19 && !c.getLsbD 38 && !c.getLsbD 63) || (!c.getLsbD 2 && c.getLsbD 4 && !c.getLsbD 13 && !c.getLsbD 19 && !c.getLsbD 38 && !c.getLsbD 63) || (!c.getLsbD 2 && !c.getLsbD 4 && c.getLsbD 13 && !c.getLsbD 19 && !c.getLsbD 38 && !c.getLsbD 63) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 13 && c.getLsbD 19 && !c.getLsbD 38 && !c.getLsbD 63) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 13 && !c.getLsbD 19 && c.getLsbD 38 && !c.getLsbD 63) || (!c.getLsbD 2 && !c.getLsbD 4 && !c.getLsbD 13 && !c.getLsbD 19 && !c.getLsbD 38 && c.getLsbD 63)) &&
   ((c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 10 && !c.getLsbD 16 && !c.getLsbD 37 && !c.getLsbD 59) || (!c.getLsbD 2 && c.getLsbD 5 && !c.getLsbD 10 && !c.getLsbD 16 && !c.getLsbD 37 && !c.getLsbD 59) || (!c.getLsbD 2 && !c.getLsbD 5 && c.getLsbD 10 && !c.getLsbD 16 && !c.getLsbD 37 && !c.getLsbD 59) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 10 && c.getLsbD 16 && !c.getLsbD 37 && !c.getLsbD 59) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 10 && !c.getLsbD 16 && c.getLsbD 37 && !c.getLsbD 59) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 10 && !c.getLsbD 16 && !c.getLsbD 37 && c.getLsbD 59)) &&
   ((c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 10 && !c.getLsbD 17 && !c.getLsbD 36 && !c.getLsbD 58) || (!c.getLsbD 2 && c.getLsbD 5 && !c.getLsbD 10 && !c.getLsbD 17 && !c.getLsbD 36 && !c.getLsbD 58) || (!c.getLsbD 2 && !c.getLsbD 5 && c.getLsbD 10 && !c.getLsbD 17 && !c.getLsbD 36 && !c.getLsbD 58) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 10 && c.getLsbD 17 && !c.getLsbD 36 && !c.getLsbD 58) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 10 && !c.getLsbD 17 && c.getLsbD 36 && !c.getLsbD 58) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 10 && !c.getLsbD 17 && !c.getLsbD 36 && c.getLsbD 58)) &&
   ((c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 11 && !c.getLsbD 16 && !c.getLsbD 35 && !c.getLsbD 61) || (!c.getLsbD 2 && c.getLsbD 5 && !c.getLsbD 11 && !c.getLsbD 16 && !c.getLsbD 35 && !c.getLsbD 61) || (!c.getLsbD 2 && !c.getLsbD 5 && c.getLsbD 11 && !c.getLsbD 16 && !c.getLsbD 35 && !c.getLsbD 61) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 11 && c.getLsbD 16 && !c.getLsbD 35 && !c.getLsbD 61) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 11 && !c.getLsbD 16 && c.getLsbD 35 && !c.getLsbD 61) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 11 && !c.getLsbD 16 && !c.getLsbD 35 && c.getLsbD 61)) &&
   ((c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 11 && !c.getLsbD 17 && !c.getLsbD 34 && !c.getLsbD 60) || (!c.getLsbD 2 && c.getLsbD 5 && !c.getLsbD 11 && !c.getLsbD 17 && !c.getLsbD 34 && !c.getLsbD 60) || (!c.getLsbD 2 && !c.getLsbD 5 && c.getLsbD 11 && !c.getLsbD 17 && !c.getLsbD 34 && !c.getLsbD 60) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 11 && c.getLsbD 17 && !c.getLsbD 34 && !c.getLsbD 60) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 11 && !c.getLsbD 17 && c.getLsbD 34 && !c.getLsbD 60) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 11 && !c.getLsbD 17 && !c.getLsbD 34 && c.getLsbD 60)) &&
   ((c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 12 && !c.getLsbD 14 && !c.getLsbD 37 && !c.getLsbD 60) || (!c.getLsbD 2 && c.getLsbD 5 && !c.getLsbD 12 && !c.getLsbD 14 && !c.getLsbD 37 && !c.getLsbD 60) || (!c.getLsbD 2 && !c.getLsbD 5 && c.getLsbD 12 && !c.getLsbD 14 && !c.getLsbD 37 && !c.getLsbD 60) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 12 && c.getLsbD 14 && !c.getLsbD 37 && !c.getLsbD 60) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 12 && !c.getLsbD 14 && c.getLsbD 37 && !c.getLsbD 60) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 12 && !c.getLsbD 14 && !c.getLsbD 37 && c.getLsbD 60)) &&
   ((c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 12 && !c.getLsbD 15 && !c.getLsbD 36 && !c.getLsbD 61) || (!c.getLsbD 2 && c.getLsbD 5 && !c.getLsbD 12 && !c.getLsbD 15 && !c.getLsbD 36 && !c.getLsbD 61) || (!c.getLsbD 2 && !c.getLsbD 5 && c.getLsbD 12 && !c.getLsbD 15 && !c.getLsbD 36 && !c.getLsbD 61) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 12 && c.getLsbD 15 && !c.getLsbD 36 && !c.getLsbD 61) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 12 && !c.getLsbD 15 && c.getLsbD 36 && !c.getLsbD 61) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 12 && !c.getLsbD 15 && !c.getLsbD 36 && c.getLsbD 61)) &&
   ((c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 13 && !c.getLsbD 14 && !c.getLsbD 35 && !c.getLsbD 58) || (!c.getLsbD 2 && c.getLsbD 5 && !c.getLsbD 13 && !c.getLsbD 14 && !c.getLsbD 35 && !c.getLsbD 58) || (!c.getLsbD 2 && !c.getLsbD 5 && c.getLsbD 13 && !c.getLsbD 14 && !c.getLsbD 35 && !c.getLsbD 58) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 13 && c.getLsbD 14 && !c.getLsbD 35 && !c.getLsbD 58) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 13 && !c.getLsbD 14 && c.getLsbD 35 && !c.getLsbD 58) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 13 && !c.getLsbD 14 && !c.getLsbD 35 && c.getLsbD 58)) &&
   ((c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 13 && !c.getLsbD 15 && !c.getLsbD 34 && !c.getLsbD 59) || (!c.getLsbD 2 && c.getLsbD 5 && !c.getLsbD 13 && !c.getLsbD 15 && !c.getLsbD 34 && !c.getLsbD 59) || (!c.getLsbD 2 && !c.getLsbD 5 && c.getLsbD 13 && !c.getLsbD 15 && !c.getLsbD 34 && !c.getLsbD 59) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 13 && c.getLsbD 15 && !c.getLsbD 34 && !c.getLsbD 59) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 13 && !c.getLsbD 15 && c.getLsbD 34 && !c.getLsbD 59) || (!c.getLsbD 2 && !c.getLsbD 5 && !c.getLsbD 13 && !c.getLsbD 15 && !c.getLsbD 34 && c.getLsbD 59)) &&
   ((c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 6 && !c.getLsbD 20 && !c.getLsbD 33 && !c.getLsbD 55) || (!c.getLsbD 3 && c.getLsbD 4 && !c.getLsbD 6 && !c.getLsbD 20 && !c.getLsbD 33 && !c.getLsbD 55) || (!c.getLsbD 3 && !c.getLsbD 4 && c.getLsbD 6 && !c.getLsbD 20 && !c.getLsbD 33 && !c.getLsbD 55) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 6 && c.getLsbD 20 && !c.getLsbD 33 && !c.getLsbD 55) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 6 && !c.getLsbD 20 && c.getLsbD 33 && !c.getLsbD 55) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 6 && !c.getLsbD 20 && !c.getLsbD 33 && c.getLsbD 55)) &&
   ((c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 6 && !c.getLsbD 21 && !c.getLsbD 32 && !c.getLsbD 54) || (!c.getLsbD 3 && c.getLsbD 4 && !c.getLsbD 6 && !c.getLsbD 21 && !c.getLsbD 32 && !c.getLsbD 54) || (!c.getLsbD 3 && !c.getLsbD 4 && c.getLsbD 6 && !c.getLsbD 21 && !c.getLsbD 32 && !c.getLsbD 54) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 6 && c.getLsbD 21 && !c.getLsbD 32 && !c.getLsbD 54) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 6 && !c.getLsbD 21 && c.getLsbD 32 && !c.getLsbD 54) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 6 && !c.getLsbD 21 && !c.getLsbD 32 && c.getLsbD 54)) &&
   ((c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 7 && !c.getLsbD 20 && !c.getLsbD 31 && !c.getLsbD 57) || (!c.getLsbD 3 && c.getLsbD 4 && !c.getLsbD 7 && !c.getLsbD 20 && !c.getLsbD 31 && !c.getLsbD 57) || (!c.getLsbD 3 && !c.getLsbD 4 && c.getLsbD 7 && !c.getLsbD 20 && !c.getLsbD 31 && !c.getLsbD 57) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 7 && c.getLsbD 20 && !c.getLsbD 31 && !c.getLsbD 57) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 7 && !c.getLsbD 20 && c.getLsbD 31 && !c.getLsbD 57) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 7 && !c.getLsbD 20 && !c.getLsbD 31 && c.getLsbD 57)) &&
   ((c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 7 && !c.getLsbD 21 && !c.getLsbD 30 && !c.getLsbD 56) || (!c.getLsbD 3 && c.getLsbD 4 && !c.getLsbD 7 && !c.getLsbD 21 && !c.getLsbD 30 && !c.getLsbD 56) || (!c.getLsbD 3 && !c.getLsbD 4 && c.getLsbD 7 && !c.getLsbD 21 && !c.getLsbD 30 && !c.getLsbD 56) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 7 && c.getLsbD 21 && !c.getLsbD 30 && !c.getLsbD 56) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 7 && !c.getLsbD 21 && c.getLsbD 30 && !c.getLsbD 56) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 7 && !c.getLsbD 21 && !c.getLsbD 30 && c.getLsbD 56)) &&
   ((c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 8 && !c.getLsbD 18 && !c.getLsbD 33 && !c.getLsbD 56) || (!c.getLsbD 3 && c.getLsbD 4 && !c.getLsbD 8 && !c.getLsbD 18 && !c.getLsbD 33 && !c.getLsbD 56) || (!c.getLsbD 3 && !c.getLsbD 4 && c.getLsbD 8 && !c.getLsbD 18 && !c.getLsbD 33 && !c.getLsbD 56) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 8 && c.getLsbD 18 && !c.getLsbD 33 && !c.getLsbD 56) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 8 && !c.getLsbD 18 && c.getLsbD 33 && !c.getLsbD 56) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 8 && !c.getLsbD 18 && !c.getLsbD 33 && c.getLsbD 56)) &&
   ((c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 8 && !c.getLsbD 19 && !c.getLsbD 32 && !c.getLsbD 57) || (!c.getLsbD 3 && c.getLsbD 4 && !c.getLsbD 8 && !c.getLsbD 19 && !c.getLsbD 32 && !c.getLsbD 57) || (!c.getLsbD 3 && !c.getLsbD 4 && c.getLsbD 8 && !c.getLsbD 19 && !c.getLsbD 32 && !c.getLsbD 57) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 8 && c.getLsbD 19 && !c.getLsbD 32 && !c.getLsbD 57) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 8 && !c.getLsbD 19 && c.getLsbD 32 && !c.getLsbD 57) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 8 && !c.getLsbD 19 && !c.getLsbD 32 && c.getLsbD 57)) &&
   ((c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 9 && !c.getLsbD 18 && !c.getLsbD 31 && !c.getLsbD 54) || (!c.getLsbD 3 && c.getLsbD 4 && !c.getLsbD 9 && !c.getLsbD 18 && !c.getLsbD 31 && !c.getLsbD 54) || (!c.getLsbD 3 && !c.getLsbD 4 && c.getLsbD 9 && !c.getLsbD 18 && !c.getLsbD 31 && !c.getLsbD 54) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 9 && c.getLsbD 18 && !c.getLsbD 31 && !c.getLsbD 54) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 9 && !c.getLsbD 18 && c.getLsbD 31 && !c.getLsbD 54) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 9 && !c.getLsbD 18 && !c.getLsbD 31 && c.getLsbD 54)) &&
   ((c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 9 && !c.getLsbD 19 && !c.getLsbD 30 && !c.getLsbD 55) || (!c.getLsbD 3 && c.getLsbD 4 && !c.getLsbD 9 && !c.getLsbD 19 && !c.getLsbD 30 && !c.getLsbD 55) || (!c.getLsbD 3 && !c.getLsbD 4 && c.getLsbD 9 && !c.getLsbD 19 && !c.getLsbD 30 && !c.getLsbD 55) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 9 && c.getLsbD 19 && !c.getLsbD 30 && !c.getLsbD 55) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 9 && !c.getLsbD 19 && c.getLsbD 30 && !c.getLsbD 55) || (!c.getLsbD 3 && !c.getLsbD 4 && !c.getLsbD 9 && !c.getLsbD 19 && !c.getLsbD 30 && c.getLsbD 55)) &&
   ((c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 16 && !c.getLsbD 29 && !c.getLsbD 51) || (!c.getLsbD 3 && c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 16 && !c.getLsbD 29 && !c.getLsbD 51) || (!c.getLsbD 3 && !c.getLsbD 5 && c.getLsbD 6 && !c.getLsbD 16 && !c.getLsbD 29 && !c.getLsbD 51) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 6 && c.getLsbD 16 && !c.getLsbD 29 && !c.getLsbD 51) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 16 && c.getLsbD 29 && !c.getLsbD 51) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 16 && !c.getLsbD 29 && c.getLsbD 51)) &&
   ((c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 17 && !c.getLsbD 28 && !c.getLsbD 50) || (!c.getLsbD 3 && c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 17 && !c.getLsbD 28 && !c.getLsbD 50) || (!c.getLsbD 3 && !c.getLsbD 5 && c.getLsbD 6 && !c.getLsbD 17 && !c.getLsbD 28 && !c.getLsbD 50) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 6 && c.getLsbD 17 && !c.getLsbD 28 && !c.getLsbD 50) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 17 && c.getLsbD 28 && !c.getLsbD 50) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 17 && !c.getLsbD 28 && c.getLsbD 50)) &&
   ((c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 16 && !c.getLsbD 27 && !c.getLsbD 53) || (!c.getLsbD 3 && c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 16 && !c.getLsbD 27 && !c.getLsbD 53) || (!c.getLsbD 3 && !c.getLsbD 5 && c.getLsbD 7 && !c.getLsbD 16 && !c.getLsbD 27 && !c.getLsbD 53) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 7 && c.getLsbD 16 && !c.getLsbD 27 && !c.getLsbD 53) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 16 && c.getLsbD 27 && !c.getLsbD 53) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 16 && !c.getLsbD 27 && c.getLsbD 53)) &&
   ((c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 17 && !c.getLsbD 26 && !c.getLsbD 52) || (!c.getLsbD 3 && c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 17 && !c.getLsbD 26 && !c.getLsbD 52) || (!c.getLsbD 3 && !c.getLsbD 5 && c.getLsbD 7 && !c.getLsbD 17 && !c.getLsbD 26 && !c.getLsbD 52) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 7 && c.getLsbD 17 && !c.getLsbD 26 && !c.getLsbD 52) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 17 && c.getLsbD 26 && !c.getLsbD 52) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 17 && !c.getLsbD 26 && c.getLsbD 52)) &&
   ((c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 14 && !c.getLsbD 29 && !c.getLsbD 52) || (!c.getLsbD 3 && c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 14 && !c.getLsbD 29 && !c.getLsbD 52) || (!c.getLsbD 3 && !c.getLsbD 5 && c.getLsbD 8 && !c.getLsbD 14 && !c.getLsbD 29 && !c.getLsbD 52) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 8 && c.getLsbD 14 && !c.getLsbD 29 && !c.getLsbD 52) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 14 && c.getLsbD 29 && !c.getLsbD 52) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 14 && !c.getLsbD 29 && c.getLsbD 52)) &&
   ((c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 15 && !c.getLsbD 28 && !c.getLsbD 53) || (!c.getLsbD 3 && c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 15 && !c.getLsbD 28 && !c.getLsbD 53) || (!c.getLsbD 3 && !c.getLsbD 5 && c.getLsbD 8 && !c.getLsbD 15 && !c.getLsbD 28 && !c.getLsbD 53) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 8 && c.getLsbD 15 && !c.getLsbD 28 && !c.getLsbD 53) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 15 && c.getLsbD 28 && !c.getLsbD 53) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 15 && !c.getLsbD 28 && c.getLsbD 53)) &&
   ((c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 14 && !c.getLsbD 27 && !c.getLsbD 50) || (!c.getLsbD 3 && c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 14 && !c.getLsbD 27 && !c.getLsbD 50) || (!c.getLsbD 3 && !c.getLsbD 5 && c.getLsbD 9 && !c.getLsbD 14 && !c.getLsbD 27 && !c.getLsbD 50) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 9 && c.getLsbD 14 && !c.getLsbD 27 && !c.getLsbD 50) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 14 && c.getLsbD 27 && !c.getLsbD 50) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 14 && !c.getLsbD 27 && c.getLsbD 50)) &&
   ((c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 15 && !c.getLsbD 26 && !c.getLsbD 51) || (!c.getLsbD 3 && c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 15 && !c.getLsbD 26 && !c.getLsbD 51) || (!c.getLsbD 3 && !c.getLsbD 5 && c.getLsbD 9 && !c.getLsbD 15 && !c.getLsbD 26 && !c.getLsbD 51) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 9 && c.getLsbD 15 && !c.getLsbD 26 && !c.getLsbD 51) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 15 && c.getLsbD 26 && !c.getLsbD 51) || (!c.getLsbD 3 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 15 && !c.getLsbD 26 && c.getLsbD 51)) &&
   ((c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 12 && !c.getLsbD 25 && !c.getLsbD 47) || (!c.getLsbD 4 && c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 12 && !c.getLsbD 25 && !c.getLsbD 47) || (!c.getLsbD 4 && !c.getLsbD 5 && c.getLsbD 6 && !c.getLsbD 12 && !c.getLsbD 25 && !c.getLsbD 47) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 6 && c.getLsbD 12 && !c.getLsbD 25 && !c.getLsbD 47) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 12 && c.getLsbD 25 && !c.getLsbD 47) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 12 && !c.getLsbD 25 && c.getLsbD 47)) &&
   ((c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 13 && !c.getLsbD 24 && !c.getLsbD 46) || (!c.getLsbD 4 && c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 13 && !c.getLsbD 24 && !c.getLsbD 46) || (!c.getLsbD 4 && !c.getLsbD 5 && c.getLsbD 6 && !c.getLsbD 13 && !c.getLsbD 24 && !c.getLsbD 46) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 6 && c.getLsbD 13 && !c.getLsbD 24 && !c.getLsbD 46) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 13 && c.getLsbD 24 && !c.getLsbD 46) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 6 && !c.getLsbD 13 && !c.getLsbD 24 && c.getLsbD 46)) &&
   ((c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 12 && !c.getLsbD 23 && !c.getLsbD 49) || (!c.getLsbD 4 && c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 12 && !c.getLsbD 23 && !c.getLsbD 49) || (!c.getLsbD 4 && !c.getLsbD 5 && c.getLsbD 7 && !c.getLsbD 12 && !c.getLsbD 23 && !c.getLsbD 49) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 7 && c.getLsbD 12 && !c.getLsbD 23 && !c.getLsbD 49) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 12 && c.getLsbD 23 && !c.getLsbD 49) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 12 && !c.getLsbD 23 && c.getLsbD 49)) &&
   ((c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 13 && !c.getLsbD 22 && !c.getLsbD 48) || (!c.getLsbD 4 && c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 13 && !c.getLsbD 22 && !c.getLsbD 48) || (!c.getLsbD 4 && !c.getLsbD 5 && c.getLsbD 7 && !c.getLsbD 13 && !c.getLsbD 22 && !c.getLsbD 48) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 7 && c.getLsbD 13 && !c.getLsbD 22 && !c.getLsbD 48) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 13 && c.getLsbD 22 && !c.getLsbD 48) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 7 && !c.getLsbD 13 && !c.getLsbD 22 && c.getLsbD 48)) &&
   ((c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 10 && !c.getLsbD 25 && !c.getLsbD 48) || (!c.getLsbD 4 && c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 10 && !c.getLsbD 25 && !c.getLsbD 48) || (!c.getLsbD 4 && !c.getLsbD 5 && c.getLsbD 8 && !c.getLsbD 10 && !c.getLsbD 25 && !c.getLsbD 48) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 8 && c.getLsbD 10 && !c.getLsbD 25 && !c.getLsbD 48) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 10 && c.getLsbD 25 && !c.getLsbD 48) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 10 && !c.getLsbD 25 && c.getLsbD 48)) &&
   ((c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 11 && !c.getLsbD 24 && !c.getLsbD 49) || (!c.getLsbD 4 && c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 11 && !c.getLsbD 24 && !c.getLsbD 49) || (!c.getLsbD 4 && !c.getLsbD 5 && c.getLsbD 8 && !c.getLsbD 11 && !c.getLsbD 24 && !c.getLsbD 49) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 8 && c.getLsbD 11 && !c.getLsbD 24 && !c.getLsbD 49) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 11 && c.getLsbD 24 && !c.getLsbD 49) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 8 && !c.getLsbD 11 && !c.getLsbD 24 && c.getLsbD 49)) &&
   ((c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 10 && !c.getLsbD 23 && !c.getLsbD 46) || (!c.getLsbD 4 && c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 10 && !c.getLsbD 23 && !c.getLsbD 46) || (!c.getLsbD 4 && !c.getLsbD 5 && c.getLsbD 9 && !c.getLsbD 10 && !c.getLsbD 23 && !c.getLsbD 46) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 9 && c.getLsbD 10 && !c.getLsbD 23 && !c.getLsbD 46) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 10 && c.getLsbD 23 && !c.getLsbD 46) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 10 && !c.getLsbD 23 && c.getLsbD 46)) &&
   ((c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 11 && !c.getLsbD 22 && !c.getLsbD 47) || (!c.getLsbD 4 && c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 11 && !c.getLsbD 22 && !c.getLsbD 47) || (!c.getLsbD 4 && !c.getLsbD 5 && c.getLsbD 9 && !c.getLsbD 11 && !c.getLsbD 22 && !c.getLsbD 47) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 9 && c.getLsbD 11 && !c.getLsbD 22 && !c.getLsbD 47) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 11 && c.getLsbD 22 && !c.getLsbD 47) || (!c.getLsbD 4 && !c.getLsbD 5 && !c.getLsbD 9 && !c.getLsbD 11 && !c.getLsbD 22 && c.getLsbD 47)))
  = false := by
  intro c
  bv_decide

/-!
## References

### Kochen-Specker Theorem and Contextuality
- Kochen, S. and Specker, E.P. (1967). "The Problem of Hidden Variables in Quantum Mechanics", *J. Math. Mech.* 17, 59–87. (Original paper on the KS theorem)
- Cortez, A., Morales, J. and Reyes, A. (2025). "Minimal ring extensions of the integers exhibiting Kochen-Specker contextuality". arXiv:2211.13216, Theorem 5(2). (Source of the SAT construction used in this file)

### SAT Proofs and Lean 4 Tactics
- Lean 4 `bv_decide` tactic: CaDiCaL SAT solver + LRAT proof certificate verification. cf. Lean 4 official documentation: https://leanprover.github.io

### Inter-Module Connections
- **Preceding**: `_01_TQC/_01_Cl8E8H84.lean` — Algebraic foundation of H(8,4)
- **Following**: `_02_BellSAT/_01_QuantumCHSH.lean` — Formal proof of the CHSH quantum violation
- **Following**: `_02_BellSAT/_02_KSTheory.lean` — Pedagogical exposition of the KS theorem

-/

end CL8E8TQC.BellSAT.CortezKS
